language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t guk0/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true guk0/react-test-app npm run test

after_success:
  - docker build -t guk0/docker-frontend ./frontend
  - docker build -t guk0/docker-backend ./backend
  - docker build -t guk0/docker-nginx ./nginx

  - echo "$Docker_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin
  - docker push guk0/docker-frontend
  - docker push guk0/docker-backend
  - docker push guk0/docker-nginx