version: "3.9"

services: 
  frontend:
    image: "guk0/docker-frontend"
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true
    mem_limit: 128m

  nginx:
    restart: always
    image: "guk0/docker-nginx"
    build: 
      dockerfile: Dockerfile
      context: ./nginx
    ports: 
      - "80:80"
    mem_limit: 128m
    links:
      - frontend
      - backend
    depends_on: 
      - mysql
      - backend


  # mysql:
  #   platform: linux/x86_64
  #   build:
  #     dockerfile: Dockerfile
  #     context: ./mysql     
  #   restart: unless-stopped
  #   container_name: app_mysql
  #   command: --default-authentication-plugin=mysql_native_password
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - ./mysql/mysql_data:/var/lib/mysql
  #     - ./mysql/sqls/:/docker-entrypoint-initdb.d/
  #   environment:
  #     MYSQL_ROOT_PASSWORD: "1234"
  #     MYSQL_DATABASE: "myapp"
  #     MYSQL_ROOT_HOST: "%"

  backend:
    image: "guk0/docker-backend"
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    container_name: app_backend
    volumes:
      - /app/node_modules
      - ./backend:/app
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: docker-fullstack-mysql.ca2ml98gsvmh.ap-northeast-2.rds.amazonaws.com
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: guk01234
      MYSQL_DATABASE: myapp
      MYSQL_PORT: 3306
    mem_limit: 128m