version: "2.4"

services: 
  frontend:
    image: "guk0/docker-frontend"
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true
    mem_limit: 128m

  nginx:
    restart: always
    image: "guk0/docker-nginx"
    build: 
      dockerfile: Dockerfile
      context: ./nginx
    ports: 
      - "80:80"
    mem_limit: 128m
    links:
      - frontend
      - backend
    depends_on: 
      - backend
      
  backend:
    image: "guk0/docker-backend"
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    container_name: app_backend
    volumes:
      - /app/node_modules
      - ./backend:/app
    mem_limit: 128m